language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-react-demos' ]; then cd .. && eval "mv $currentfolder generator-react-demos" && cd generator-react-demos; fi

